name: eslint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install NVM
        run: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - name: Reload shell to use nvm
        run: . "$NVM_DIR/nvm.sh"
      - name: Install dependencies
        run: npm install
      - name: Lint source code
        run: npm run lint
